### ISSUE TITLE
License is not DFSG-complaint

### ISSUE THREAD

**Issue by lamby** [typeintandem/tandem#131]
Hi,

Unfortunately, due to the following clause:

```
     (e) Any Derivative Works may not be configured to use the default server
         provided by the Copyright holders. You must configure all Derivative
         Works to use servers owned by You, or servers You are otherwise
         authorized to use.
```

... typetandem is not in compliance with (at least) the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines). It would also not be compliant with the [FSF's Four Freedoms](https://www.gnu.org/philosophy/free-sw.en.html).

This is a shame as typetandem is genuinely cool but Debian (and others) simply cannot distribute it. :(

**Comment by lamby** [comment]
> We would have to setup our own debian-specific relay server to comply with the license

The important point is that the clause is not DFSG #6 and FSF Freedom Zero, not the specifics of custom servers (I fear this might be a distraction).

**Comment by jfrederickson** [comment]
Note that it would be perfectly valid to state in the ToS for your official servers that you may only use unmodified copies of the software with the official servers. This would ensure that the license is GPL-compatible while still restricting the use of modified versions with the official servers - so long as the software license itself doesn't have the restriction, it should be fine as far as the GPL/DFSG/etc. are concerned.

**Comment by lamby** [comment]
(This is not a GPL-compatibility issue, it is a fundamental free/open source issue..)

**Comment by anarcat** [comment]
well, i must say i wouldn't mind if the servers had terms of service that would forbid derivatives, to be honest: that's up to whoever is running the service, and would be a better place to put such policy, assuming you really need such a policy, than the license file, which needlessly restricts freedom.

in other words, if you want to run a private server, run a private server, and do that through a terms of service change. don't cripple the license, because that will severely adoption of the protocol, and I doubt you want that.

**Comment by geoffxy** [comment]
Hey everyone - thanks for bringing this up!

As many of you have already deduced, the reason we added the extra clause was because we were concerned about supporting the loads of modified clients on our rendezvous server. We want to provide a good user experience for everyone using Tandem, and it would be difficult to do that by supporting modified clients. The spirit of the license was not to stifle the development or distribution of Tandem.

With that said, we’ve heard your feedback and agree that this kind of stipulation is better suited for a terms of service on the server we host. So we’ll be switching to the unmodified Apache 2.0 license and adding a terms of service to request users of modified versions of Tandem to use their own hosted server.

**Comment by lamby** [comment]
Awesome, thank you for this @geoffxy  :)

**Comment by rageandqq** [comment]
Hey @lamby , we updated our License in this mono repo, as well as in our [vim](https://github.com/typeintandem/vim), [nvim](https://github.com/typeintandem/nvim) and [sublime](https://github.com/typeintandem/sublime) release repositories, so I'll close this issue out for now.

Thanks again for your interest in Tandem!
