### ISSUE TITLE
question: plan for a web client?

### ISSUE THREAD

**Issue by monperrus** [typeintandem/tandem#134]
Is there a plan to have Javascript web client? Is that on the roadmap?

**Comment by rageandqq** [comment]
Hi @monperrus , thanks for the interest in Tandem! Our team is overwhelmed by the positive response we've received from the community.

We currently have a lot of outstanding issues that we want to address first before adding on other editors ourselves, so it will take a while for us to circle back to this. Additionally, we originally built Tandem as a native solution. Given that Tandem's current architecture requires the ability for a plugin to spawn a local agent process (something that is restricted by browsers for security reasons) and we'd have to rethink how Tandem is built in order to support this.

That being said, if you are interested in developing a plugin for Tandem and somehow getting it to run on the web, we'd be delighted to help out along the way and welcome pull requests. We wrote a guide to aid in developing Tandem plugins. Check out our wiki: https://github.com/typeintandem/tandem/wiki/Interacting-with-the-Tandem-Agent

**Comment by monperrus** [comment]
Thanks for your answer!
